version: '3.3'

services:
  php:
      build:
        context: .
        dockerfile: dockerfile
      container_name: php-PokeFight
      depends_on:
      - db-PokeFight
      image: php:8.0-apache
      volumes:
      - ./php:/var/www/html/
      ports:
      - 80:80
  db-PokeFight:
      container_name: mysql-PokeFight
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment: 
        MYSQL_ROOT_PASSWORD: sdfjqgsfhg987
        MYSQL_DATABASE: PokeFight
        MYSQL_USER: Albrizio
        MYSQL_PASSWORD: pokemon1234
      ports:
      - 3306:3306
  phpmya:
      image: phpmyadmin/phpmyadmin:latest
      container_name: PHPmyADMIN-PokeFight
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db-PokeFight
        PMA_USER: Albrizio
        PMA_PASSWORD: pokemon1234
        UPLOAD_LIMIT: 320M
      ports:
      - 8899:80